FORMAT: 1A

# Reactive REST template
This template is example of reactive REST service builded with Play2 Framework.

# Group Test
Test API object

## Notes Collection [/v1/test]
### List all Test objects [GET]
+ Response 200 (application/json)

        [{
          "id": 1, "title": "Jogging in park"
        }, {
          "id": 2, "title": "Pick-up posters from post-office"
        }]

### Create Test object [POST]
+ Request (application/json)

        { "title": "Buy cheese and bread for breakfast." }

+ Response 201 (application/json)

        { "id": 3, "title": "Buy cheese and bread for breakfast." }

## Note [/v1/test/{id}]
A single Test object with all its details

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the Note to perform action with. Has example value.

### Retrieve a Test object [GET]
+ Response 200 (application/json)

            { "id": 2, "title": "Pick-up posters from post-office" }

### Remove a Test object [DELETE]
+ Response 204
