FORMAT: 1A

# Reactive REST template
This template is example of reactive REST service builded with Play2 Framework.

# Group Test
Test API object

## Test collection [/api/v1/testObject]
### List all Test objects [GET]
+ Response 200 (application/json)

        [{
          "_id": "54f8806b5000004401581de4", "title": "Test", "uniqueField": "unique", "age": 18
        }, {
          "_id": "54f891165000004f02581de9", "title": "Test", "uniqueField": "unique1", "age": 18
        }]


### Create Test object [POST]
+ Request (application/json)

        {"title": "Test", "uniqueField": "unique", "age": 18 }

+ Response 201 (application/json)

        { "_id": "54f8806b5000004401581de4", "title": "Test", "uniqueField": "unique", "age": 18 }

## Test object [/api/v1/testObject/{id}]
A single Test object with all its details

+ Parameters
    + id (required, string, `54f8806b5000004401581de4`) ... String `id` of the object to perform action with. Has example value.

### Retrieve a Test object [GET]
+ Response 200 (application/json)

            { "_id": "54f8806b5000004401581de4", "title": "Test", "uniqueField": "unique", "age": 18 }

### Remove a Test object [DELETE]
+ Response 204
